### ISSUE TITLE
No devices/entities present in dashboard or otherwise

### ISSUE THREAD

**Issue by fordaj** [thecode/ha-rpi_gpio#100]
Hi! I'm running Home Assistant v2022.8.6 in a docker container. I've installed HACS and `rpi_gpio`, and have the following `configuration.yaml`:
```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

# RPi GPIO
switch:
  - platform: rpi_gpio
    switches:
      - port: 21
        name: "Stove"
        unique_id: "stove"
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

HA UI shows I've got a valid config with RPi GPIO Entities, but "Stove" is not showing up anywhere in home assistant. Any suggestions?
