### ISSUE TITLE
Controlling PWM fan on Pi4

### ISSUE THREAD

**Issue by slyhne** [thecode/ha-rpi_gpio#11]
With the old rpi_gpio integration I could control my pwm fan locally on my RPi4. 

```
light:
  - platform: rpi_gpio_pwm
    leds:
      - name: RPI Cooling Fan
        driver: gpio
        pins: [18]
        type: simple
```

Then I could control my fan speed as if it was a light bulb with automations.

Will this integration be able to do the same. And if so, can you give an example?
