### ISSUE TITLE
Can't add a switch

### ISSUE THREAD

**Issue by OZ1SEJ** [thecode/ha-rpi_gpio#124]
I want to control the CPU fan on my Raspberry Pi 3, so I've added the Home Assistant Raspberry Pi GPIO custom integration through HACS. Then I've added the following to `/root/config/configuration.yaml`:

```
switch:
  - platform: rpi_gpio
    switches:
      - port: 3
        name: "Fan"
```
I've restarted Home Assistant, but I don't have an entity called "Fan". Also, there's nothing in the log about "fan" or "gpio". What am I doing wrong?
