### ISSUE TITLE
Using single relay

### ISSUE THREAD

**Issue by Segilmez06** [thecode/ha-rpi_gpio#144]
I've connected a single relay on GPIO17 and trying to control it. I tried to change `invert_logic` but it didn't work. What should I do to handle the relay?

```yaml
switch:
  - platform: rpi_gpio
    switches:
      - port: 17
        name: "Led Strip Relay"
        unique_id: "white_led_strip"
        invert_logic: true
```
