### ISSUE TITLE
Unable to use switch

### ISSUE THREAD

**Issue by LooperX** [thecode/ha-rpi_gpio#145]
Unable to use this component due to following error on startup:

> File "/config/custom_components/rpi_gpio/__init__.py", line 33, in setup
>     GPIO.setmode(GPIO.BCM)
> AttributeError: module 'RPi.GPIO' has no attribute 'setmode'

Called with:
```
switch:
  - platform: rpi_gpio
    switches:
      - port: 11
        name: "Fan Office"
      - port: 12
        name: "Light Desk"
```

Already tried to update RPi libraries
