### ISSUE TITLE
No Inputs working - Outputs are ok

### ISSUE THREAD

**Issue by gang-himself** [thecode/ha-rpi_gpio#203]
Today I did a huge update, since I didn't update the last two years...

Now I'm on 
Home Assistant 2023.10.1 
Supervisor 2023.10.0
on a Rpi4 with RaspberryOS 11 (bullseye).
I installed ha-rpi_gpio with HACS, since the original one got lost in this update.
I also changed the config file according to the documentation of the custom integration.

```
switch:
  - platform: rpi_gpio
    switches:
      - port: 23
        name: "Garagentor"
        invert_logic: true
binary_sensor:
  - platform: rpi_gpio
    sensors:
      - port: 26
        name: "PV_Zaehler"
        bouncetime: 2000
        invert_logic: true
```

Now the one switch I have (on GPO23) is working, but the one sensor I have (on GPI26) isn't.
There is no error message in the logs, the entity does exist, but it never changes its state.

I didn't touch the installation and it worked until the update.

Can anybody help me out, as I don't actually know where to search. 
Of course I tried to find an answer in the www, but didn't...

Greetings

**Comment by gang-himself** [comment]
I switched to remote-rpi_gpio, this works.

**Comment by VladNord** [comment]
> I switched to remote-rpi_gpio, this works.
Having same issues. 

Can you please provide config for binary_sensor.
I wonder how to implement remote-rpi_gpio on localhost with bouncing options.

**Comment by gang-himself** [comment]
```
binary_sensor:
  - platform: remote_rpi_gpio
    host: localhost
    ports:
      26: PV_Zaehler

```
Looks like the remote-integration doesn't have bouncing options.
In fact, I just left out the previously used option, but it is surprisingly no more needed. It works better than before.
It seems, the remote-integration has internally different bouncing-routines.
