### ISSUE TITLE
Generic Switch Not Working

### ISSUE THREAD

**Issue by samirg1** [thecode/ha-rpi_gpio#230]
I have a Raspberry Pi 4 with HA and I'm trying to make a switch for my rpi fan.
My code is this:
```
switch:
    - platform: rpi_gpio
      switches:
      - port: 2
        name: "RPi Fan"
```
I have a 2 pin 5V fan, and have connected ground to pin 6 and the power to pin 3 (port 2). 
This successfully creates a switch in HA however toggling it does nothing.

I'm new to this whole thing so any help would be greatly appreciated!
