### ISSUE TITLE
Binary input not working

### ISSUE THREAD

**Issue by VladNord** [thecode/ha-rpi_gpio#231]
```
    binary_sensor:

      - platform: rpi_gpio
        sensors:
          - port: 26
            name: doorbell_button
            bouncetime: 50
            invert_logic: true
```
Hello!

I have the following config. Everything worked fine until HA 2023.9 update. 
After this update the button stopped working and constantly in ON condition (but before it was OFF, if not pressed)

Tried different integrations (remote rpi GPIO, PiGPIO)- none of this works for me.
I use HASSOS.

Maybe someone can suggest what can i do in this case.
