### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by Pols88** [thecode/ha-rpi_gpio#316]
my configuration file has an error: Invalid config for 'switch' from integration 'rpi_gpio' at configuration.yaml, line 33: 'ports' is an invalid option for 'rpi_gpio.switch', check: ports

This is my code:

# Raspberry Pi Cooling Fan
sensor:
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
    scan_interval: 10
switch:
  - platform: rpi_gpio
    ports:
      18: RPI Cooling Fan
climate:
  - platform: generic_thermostat
    name: RPI Cooling Fan Controller
    heater: switch.rpi_cooling_fan
    target_sensor: sensor.cpu_temperature
    min_temp: 55
    max_temp: 80
    ac_mode: true
    target_temp: 55
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    min_cycle_duration:
      seconds: 30
    keep_alive:
      minutes: 5
    initial_hvac_mode: "cool"

TY

**Comment by tomer-w** [comment]
The obsolete way to configure the integration was removed.

Instead:
```
switch:
  platform: rpi_gpio
  ports:
     18: RPI Cooling Fan
```
The way to set it up correctly is:
```
switch:
  - platform: rpi_gpio
    switches:
      - port: 18
        name: "RPI Cooling Fan"
```

Please let me know if this did the trick.

**Comment by jramsgaard** [comment]
Think im seeing a bit of the same. Happend after update to HA 2024.11.1. Have tried to change "pin" to "port", but it then gives me an validation error.

<details><summary>Error:</summary>
<p>

Logger: homeassistant.components.cover
Source: helpers/entity_platform.py:365
integration: Cover (documentation, issues)
First occurred: 11:25:17 PM (1 occurrences)
Last logged: 11:25:17 PM

Error while setting up rpi_gpio platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/rpi_gpio/cover.py", line 85, in async_setup_platform
    cover.get(CONF_UNIQUE_ID) or f"{DOMAIN}_{cover.get(CONF_RELAY_PORT) or cover.get("relay_pin")}_{cover[CONF_NAME].lower().replace(' ', '_')}",
                                                       ^^^^^^^^^^^^^^^
NameError: name 'CONF_RELAY_PORT' is not defined. Did you mean: 'CONF_RELAY_PIN'?`

</p>
</details> 

Config:
```
cover:
  - platform: rpi_gpio
    state_pull_mode: 'UP'
    invert_state: true
    relay_time: 3
    covers:
      - relay_pin: 27
        state_pin: 11
        name: 'GarageDoor1'
      - relay_pin: 23
        state_pin: 12
        name: 'GarageDoor2'

```
