### ISSUE TITLE
Switch function not supported

### ISSUE THREAD

**Issue by Sacapofpc** [thecode/ha-rpi_gpio#354]
Hello, on my HA running on an RPi4, the switch function is supposedly no longer supported. The last working version is 2024.12.1.

Binary sensor works correctly.

Any ideas?

**Comment by tomer-w** [comment]
We will need the configuration and the integration logs from HA startup.

**Comment by thecode** [comment]
> Is it enough?

No, please share the configuration YAML something like:
```YAML
switch:
  - platform: rpi_gpio
    switches:
      - port: 11
        name: "Fan Office"
        unique_id: "fan_office_switch_port_11"
        persistent: true
```
