### ISSUE TITLE
Activating second binary sensor on RPI5 causes system to run incredibly slowly

### ISSUE THREAD

**Issue by andypnz** [thecode/ha-rpi_gpio#369]
Hi

Great repository thank you! Using 2025.2.1 with HA 2025.5.3 - running on a RPi5.

When I moved from RPi4 to RPi5 I had issues with GPIO - I had tried a couple of GPIO repositories - assuming all the uninstalls have been clean, I am currently using yours :-)

All has been working well with
```
switch:
  - platform: gpio
    switches:
       - port: 21
         name: "RPi Green LED"
         unique_id: "rpi_green_LED_GPIO_21"
         invert_logic: false
```

And 
```
binary_sensor:
  - platform: gpio
    sensors:
      - port: 20
        name: "Mains Power Status"
        unique_id: "rpi_power_sense_input_GPIO_20"
        bouncetime: 80
        invert_logic: true
        pull_mode: "UP"
```

But needed a second binary sensor, so changed to this:
```
binary_sensor:
  - platform: gpio
    sensors:
      - port: 26
        name: "RPi Momentary Switch"
        unique_id: "rpi_mom_switch_GPIO_26"
        bouncetime: 80
        invert_logic: true
        pull_mode: "UP"
      - port: 20
        name: "Mains Power Status"
        unique_id: "rpi_power_sense_input_GPIO_20"
        bouncetime: 80
        invert_logic: true
        pull_mode: "UP"
```

Issue: With the second binary sensor, the whole HA system goes to a crawl.... hardly functional. I remove this second binary sensor, and all is good again....

Any thoughts? Thank you!
