### ISSUE TITLE
Assigning to an area, adding unique_id

### ISSUE THREAD

**Issue by darmach** [thecode/ha-rpi_gpio#38]
Hello
First things first - this is not much of an issue, more a feature request / discussion

I am new to ha environment, and I am having problems assigning reed switches connected using this integration (via HACS) to areas.
Can't also assign unique id to do that on GUI

Is this by design or am I doing something wrong?

Current config entry is pretty simple:

```
binary_sensor:
  - platform: rpi_gpio
    bouncetime: 80
    # invert_logic: true
    # pull_mode: "DOWN"
    ports:
      16: Front doors
```
